### PR TITLE
Replace deprecated collections::Bound with ops::Bound

### PR DESCRIPTION
**Pull request by bstrie**

### CODE REVIEW

**Comment by koba-e964** [comment]
Is `collections::Bound` deprecated? I couldn't find anything in [the doc of `std::collections::Bound`](https://docs.rs/rustc-std-workspace-std/1.0.1/std/collections/enum.Bound.html).

**Comment by koba-e964** [comment]
It's deprecated indeed. (https://github.com/rust-lang/rust/blob/1.50.0/library/std/src/collections/mod.rs#L404-L406)
Sorry.
I'm wondering why it slipped off our radar.

**Review by koba-e964 — APPROVED** [review]
Thanks!

**Comment by bstrie** [comment]
>  I'm wondering why it slipped off our radar.

It's not your fault, it's actually a bug in the stdlib/compiler that I'm in the process of working on. :) https://github.com/rust-lang/rust/issues/82080

**Pull request merged**
